require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ai_interaction_logs", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # AiInteractionLog. As you add validations to AiInteractionLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AiInteractionLog.create! valid_attributes
      get ai_interaction_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ai_interaction_log = AiInteractionLog.create! valid_attributes
      get ai_interaction_log_url(ai_interaction_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ai_interaction_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ai_interaction_log = AiInteractionLog.create! valid_attributes
      get edit_ai_interaction_log_url(ai_interaction_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AiInteractionLog" do
        expect {
          post ai_interaction_logs_url, params: { ai_interaction_log: valid_attributes }
        }.to change(AiInteractionLog, :count).by(1)
      end

      it "redirects to the created ai_interaction_log" do
        post ai_interaction_logs_url, params: { ai_interaction_log: valid_attributes }
        expect(response).to redirect_to(ai_interaction_log_url(AiInteractionLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AiInteractionLog" do
        expect {
          post ai_interaction_logs_url, params: { ai_interaction_log: invalid_attributes }
        }.to change(AiInteractionLog, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ai_interaction_logs_url, params: { ai_interaction_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ai_interaction_log" do
        ai_interaction_log = AiInteractionLog.create! valid_attributes
        patch ai_interaction_log_url(ai_interaction_log), params: { ai_interaction_log: new_attributes }
        ai_interaction_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ai_interaction_log" do
        ai_interaction_log = AiInteractionLog.create! valid_attributes
        patch ai_interaction_log_url(ai_interaction_log), params: { ai_interaction_log: new_attributes }
        ai_interaction_log.reload
        expect(response).to redirect_to(ai_interaction_log_url(ai_interaction_log))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ai_interaction_log = AiInteractionLog.create! valid_attributes
        patch ai_interaction_log_url(ai_interaction_log), params: { ai_interaction_log: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ai_interaction_log" do
      ai_interaction_log = AiInteractionLog.create! valid_attributes
      expect {
        delete ai_interaction_log_url(ai_interaction_log)
      }.to change(AiInteractionLog, :count).by(-1)
    end

    it "redirects to the ai_interaction_logs list" do
      ai_interaction_log = AiInteractionLog.create! valid_attributes
      delete ai_interaction_log_url(ai_interaction_log)
      expect(response).to redirect_to(ai_interaction_logs_url)
    end
  end
end
