require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dashboard_widgets", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DashboardWidget. As you add validations to DashboardWidget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DashboardWidget.create! valid_attributes
      get dashboard_widgets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dashboard_widget = DashboardWidget.create! valid_attributes
      get dashboard_widget_url(dashboard_widget)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dashboard_widget_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      dashboard_widget = DashboardWidget.create! valid_attributes
      get edit_dashboard_widget_url(dashboard_widget)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DashboardWidget" do
        expect {
          post dashboard_widgets_url, params: { dashboard_widget: valid_attributes }
        }.to change(DashboardWidget, :count).by(1)
      end

      it "redirects to the created dashboard_widget" do
        post dashboard_widgets_url, params: { dashboard_widget: valid_attributes }
        expect(response).to redirect_to(dashboard_widget_url(DashboardWidget.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DashboardWidget" do
        expect {
          post dashboard_widgets_url, params: { dashboard_widget: invalid_attributes }
        }.to change(DashboardWidget, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dashboard_widgets_url, params: { dashboard_widget: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dashboard_widget" do
        dashboard_widget = DashboardWidget.create! valid_attributes
        patch dashboard_widget_url(dashboard_widget), params: { dashboard_widget: new_attributes }
        dashboard_widget.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dashboard_widget" do
        dashboard_widget = DashboardWidget.create! valid_attributes
        patch dashboard_widget_url(dashboard_widget), params: { dashboard_widget: new_attributes }
        dashboard_widget.reload
        expect(response).to redirect_to(dashboard_widget_url(dashboard_widget))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        dashboard_widget = DashboardWidget.create! valid_attributes
        patch dashboard_widget_url(dashboard_widget), params: { dashboard_widget: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dashboard_widget" do
      dashboard_widget = DashboardWidget.create! valid_attributes
      expect {
        delete dashboard_widget_url(dashboard_widget)
      }.to change(DashboardWidget, :count).by(-1)
    end

    it "redirects to the dashboard_widgets list" do
      dashboard_widget = DashboardWidget.create! valid_attributes
      delete dashboard_widget_url(dashboard_widget)
      expect(response).to redirect_to(dashboard_widgets_url)
    end
  end
end
