require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_settings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SystemSetting. As you add validations to SystemSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemSetting.create! valid_attributes
      get system_settings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_setting = SystemSetting.create! valid_attributes
      get system_setting_url(system_setting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_setting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      system_setting = SystemSetting.create! valid_attributes
      get edit_system_setting_url(system_setting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemSetting" do
        expect {
          post system_settings_url, params: { system_setting: valid_attributes }
        }.to change(SystemSetting, :count).by(1)
      end

      it "redirects to the created system_setting" do
        post system_settings_url, params: { system_setting: valid_attributes }
        expect(response).to redirect_to(system_setting_url(SystemSetting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemSetting" do
        expect {
          post system_settings_url, params: { system_setting: invalid_attributes }
        }.to change(SystemSetting, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post system_settings_url, params: { system_setting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_setting" do
        system_setting = SystemSetting.create! valid_attributes
        patch system_setting_url(system_setting), params: { system_setting: new_attributes }
        system_setting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_setting" do
        system_setting = SystemSetting.create! valid_attributes
        patch system_setting_url(system_setting), params: { system_setting: new_attributes }
        system_setting.reload
        expect(response).to redirect_to(system_setting_url(system_setting))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        system_setting = SystemSetting.create! valid_attributes
        patch system_setting_url(system_setting), params: { system_setting: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_setting" do
      system_setting = SystemSetting.create! valid_attributes
      expect {
        delete system_setting_url(system_setting)
      }.to change(SystemSetting, :count).by(-1)
    end

    it "redirects to the system_settings list" do
      system_setting = SystemSetting.create! valid_attributes
      delete system_setting_url(system_setting)
      expect(response).to redirect_to(system_settings_url)
    end
  end
end
